name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Arc
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/Arc
          path: Arc

      - name: Checkout Mindustry
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/Mindustry
          path: Mindustry

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Unsigned IPA
        run: |
          cd Mindustry
          chmod +x ./gradlew
          ./gradlew pack -PnoLocalArc=true
          ./gradlew --stacktrace :ios:deploy -Probovm.iosSkipSigning=true -PnoLocalArc=true

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mindustry-iOS-Unsigned
          path: Mindustry/ios/build/robovm/IOSLauncher.ipa
